### ISSUE TITLE
Subscription yields undefined

### ISSUE THREAD

**Issue by KadekM** [LukaJCB/rxscala-js#11]
`val x = Subscription.EMPTY`

yields `Uncaught TypeError: Cannot read property 'EMPTY' of undefined(…)`

`println(Subscription.toString)` yield `undefined`

**Comment by LukaJCB** [comment]
Fixed in https://github.com/LukaJCB/rxscala-js/commit/730e3c7918da9d5cf7755a813339c65682cdbe0f 

Problem was that `Subscription` doesn't exist in RxJS, only `Rx.Subscription`. Also empty subscriptions are already closed :) 
Thank you for pointing this out 👍

**Comment by KadekM** [comment]
:+1:
