### ISSUE TITLE
Not sure why my code is throwing an error

### ISSUE THREAD

**Issue by bskern** [LukaJCB/rxscala-js#14]
Hello,

I put the code in a gist along with a picture of my console and the webpage in the background. It seems its in the subscribe block and I don't get why.  

[gist](https://gist.github.com/bskern/7523a828df1bdfebb7479c8745f05b84)

Can you provide any feedback?

**Comment by LukaJCB** [comment]
`concatMap` is currently still somewhat broken, I'm working on a fix, though. In the meanwhile you can get it to work by specifying the Type parameter explicitly. 
`.concatMap[_, XMLHttpRequest](fWeather)` 
I'll release a fix for this soon, though, which will also allow you to get rid of your `notsure` parameter.

**Comment by bskern** [comment]
ok thanks! when I did do [_,XMLHttpRequest]  I got compiler error on unbound wildcard type tried flipping those around which didnt work however when both [I,R] were XMLHttpReqeust everything compiled and page worked as I expected

**Comment by LukaJCB** [comment]
Glad you got it working, and sorry for the mixup!

**Comment by LukaJCB** [comment]
Fixed now in v0.11.0! :)
