### ISSUE TITLE
MergeMap inference

### ISSUE THREAD

**Issue by KadekM** [LukaJCB/rxscala-js#15]
Same as #6, but with MergeMap... could we do something about it ? Prehaps all the ones with (T, Int) in a consistent manner (like mapWithIndex) ?

**Comment by LukaJCB** [comment]
Fixed in https://github.com/LukaJCB/rxscala-js/commit/924aa2e8dd8fcaa716ebf9f95fc9b16cfc595866 :)

**Comment by KadekM** [comment]
Thanks a lot! :+1:
