### ISSUE TITLE
Missing Observable.empty

### ISSUE THREAD

**Issue by justinwoo** [LukaJCB/rxscala-js#18]
sorry, i really haven't used scala.js much (or really scala much at all), but it seems like there's no definition for observable.empty, which is needed as a building block for flatMap and such.

could you add this operator sometime? thanks! (docs link: http://reactivex.io/rxjs/class/es6/Observable.js~Observable.html#static-method-empty)

**Comment by KadekM** [comment]
In the meantime you can use `Observable.just[T]()` to achieve that

**Comment by LukaJCB** [comment]
Fixed in https://github.com/LukaJCB/rxscala-js/commit/f2f9cd96e5807d45b7da6589a49e73d40a0c0983 :)

**Comment by justinwoo** [comment]
nice! could we also have Observable.of? iirc it's missing, and it would be nice to have it to ensure having a single value lift and would also make for a nice gateway to getting an applicative instance (? , i don't know if scala core has an applicative typeclass)

**Comment by LukaJCB** [comment]
`Observable.of` is there :)

**Comment by justinwoo** [comment]
cool, thanks!

**Comment by LukaJCB** [comment]
And no Scala core doesn't really have typeclasses, but you can check out Cats and RxScala.js-Cats here: https://github.com/KadekM/rxscala-js-cats :)
