### ISSUE TITLE
Http.get: Response.body is surrounded with doubleqoutes

### ISSUE THREAD

**Issue by gaydenko** [LukaJCB/rxscala-js#19]
... for text response (that is `Content-Type:text/plain; charset=UTF-8` explicitly added to response).

**Comment by gaydenko** [comment]
Unfortunately, it is just a top of iceberg. Just look a the fragment I am forced to use to get (this time JSON) response:
```scala
  private val updateResponses = Http.get(updateRequests).map { response =>
    val rawBody = response.body.trim
    val body = rawBody.substring(0, rawBody.size - 1).substring(1).replace("""\"""", "\"")
    parser.decode[Seq[Out]](body).getOrElse(Nil): Seq[Out]
  }
```
That is not only all the response body is surrounded with double-quotes, but all internal double-quotes are escaped with back slashes.

**Comment by LukaJCB** [comment]
Damn yeah, that looks bad, I'm gonna try and have it fixed by next week. This really shouldn't happen. I'd do it sooner, but I have two talks I have to give this week.

**Comment by gaydenko** [comment]
@LukaJCB , hope those talks are about OutWatch :) At any case - good luck!

**Comment by gaydenko** [comment]
BTW, I guess, regardless playing with JSON original response body must be passed through at any case being kept as is.
