### ISSUE TITLE
Calling Subject() from application yields exception

### ISSUE THREAD

**Issue by Narigo** [LukaJCB/rxscala-js#20]
Hi Luka, I've updated my code to 0.13.6 from 0.9.1 and now it breaks whenever I try to create a Subject by doing `Subject()`, with the following error:

```
Subject.scala:47 Uncaught TypeError: Cannot read property 'Subject' of undefined
    at $c_Lrxscalajs_Subject$.apply__Lrxscalajs_Subject (Subject.scala:47)
    at $c_Lcom_campudus_scycle_examples_ScycleApp$.main__V (ScycleApp.scala:17)
    at $c_Lcom_campudus_scycle_examples_ScycleApp$.$$js$exported$meth$main__O (ScycleApp.scala:16)
    at $c_Lcom_campudus_scycle_examples_ScycleApp$.main (ScycleApp.scala:16)
    at index-dev.html?_ijt=gotlcjc1l53nsn4srshbmuemtq:13
$c_Lrxscalajs_Subject$.apply__Lrxscalajs_Subject	@	Subject.scala:47
$c_Lcom_campudus_scycle_examples_ScycleApp$.main__V	@	ScycleApp.scala:17
$c_Lcom_campudus_scycle_examples_ScycleApp$.$$js$exported$meth$main__O	@	ScycleApp.scala:16
$c_Lcom_campudus_scycle_examples_ScycleApp$.main	@	ScycleApp.scala:16
(anonymous)	@	index-dev.html?_ijt=gotlcjc1l53nsn4srshbmuemtq:13
```

I've made changes to my project so it's only calling `Subject[Int]()` after the main export here (branch subject-apply-reproducer), so you can disregard all other code...
https://github.com/Narigo/scalajs-fun/blob/subject-apply-reproducer/scycle-examples/src/main/scala/com/campudus/scycle/examples/ScycleApp.scala#L20

I'm unsure what is different than before, but when doing the `fastOptJS` in `sbt`, it does not seem to work anymore. Did some dependency change or do I need to update something else in my [build.sbt](https://github.com/Narigo/scalajs-fun/blob/subject-apply-reproducer/build.sbt)?

**Comment by Narigo** [comment]
I think I found the problem. The `"org.webjars.npm" % "rxjs" % "5.2.0"` needs to be added not only to `"test"`! I really need to take a course in sbt.

**Comment by LukaJCB** [comment]
Glad to see you figured this out! :)
