### ISSUE TITLE
Observable.cache was removed in rxjs 5

### ISSUE THREAD

**Issue by fdietze** [LukaJCB/rxscala-js#24]
https://github.com/LukaJCB/rxscala-js/blob/7a180f15a83de6a943f3564bf62acdaeae7237b5/src/main/scala/rxscalajs/facade/ObservableFacade.scala#L53

https://github.com/ReactiveX/rxjs/blob/master/CHANGELOG.md#breaking-changes-2

**Comment by LukaJCB** [comment]
Fixed in a207f3550d8a3afcc3b74970b8e5f8c7dca981e7
