### ISSUE TITLE
ObservableFacade#concat does not enforce common supertype

### ISSUE THREAD

**Issue by connorlanigan** [LukaJCB/rxscala-js#25]
Currently, `concat` returns an observable that only conforms to the type of the added observable:
*(code simplified)*
```
class ObservableFacade[+T] ... {
...
    def concat[U](that: ObservableFacade[U], ...): ObservableFacade[U]
...
}
```
If the first observable is of a different/incompatible type, accessing the value's members will result in undefined behaviour.

From my (limited) understanding the signature would have to be changed to:
```
    def concat[U >: T](that: ObservableFacade[U]): ObservableFacade[U]
```

## SSCCE:
```
case class FirstCaseClass()
case class TotallyDifferentCaseClass(onlyInSecond: String)


val first = Observable.just(FirstCaseClass())

val second = Observable.just(TotallyDifferentCaseClass("bla"))

val concatenated = (first concat second).map(_.onlyInSecond)

div(
    child <-- concatenated
)
```

Results in the following exception: `UndefinedBehaviorError: An undefined behavior was detected: FirstCaseClass() is not an instance of example.Example$TotallyDifferentCaseClass$3`

**Comment by LukaJCB** [comment]
Fixed in 0163a113234f68550269ddbf4fe25dd5961487c6 :)
