### ISSUE TITLE
Missing return of dispose function in Observable.create

### ISSUE THREAD

**Issue by Narigo** [LukaJCB/rxscala-js#3]
I'm missing a way to add a dispose function when using `Observable.create`. According to the [RxJS documentation](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/create.md#rxobservablecreatesubscribe), it should be possible to have one here.

Is this a limitation or just not implemented (yet)?

**Comment by LukaJCB** [comment]
It's not a limitation, RxScalaJS is based on RxJS 5, where they renamed `dispose` to `unsubscribe`. 

Here's an example:

```
val observable= Observable.create[String](observer=> {
  observer.next("0")
  observer.next("1")
})

val subscription = observable.subscribe(n => println(n))
subscription.unsubscribe()
```

**Comment by Narigo** [comment]
Hmm, then I'm unsure how I can port [this CycleJS code here](https://github.com/cyclejs/cyclejs/blob/master/rxjs-adapter/src/index.ts#L10-L23) now.

After looking for RxJS 5, I found [this code](https://github.com/ReactiveX/rxjs/blob/master/src/Observable.ts#L56-L58), which appears to still let me add a custom `TeardownLogic`, which may be one of type `AnonymousSubscription`, `Function` (the one I'm searching for) or `void` (Unit).

**Comment by LukaJCB** [comment]
Ah, I see. Yeah, that's currently missing in the implementation, but it shouldn't be too difficult to get working. I can probably get it done in the next couple of weeks. You can also send a PR if you'd like. 
Are you trying to port Cycle to ScalaJs? :)

**Comment by Narigo** [comment]
Well, it's just a side project to learn ScalaJS and see how CycleJS works. I doubt that I will ever use it for something productive ;)
Maybe I can have a look into it in the next few days. As you cannot have multiple return types, how do you want the API to look like?

**Comment by LukaJCB** [comment]
Is that project on GitHub, I'd love to see :) You probably don't need the Generic Stream wrapper, unless you're going to support multiple stream libraries. Implementing the basics of Cycle could probably be around 200 LOC.

The API of `create` could take a function that returns a `Unit | js.Function0[Unit]`, think that should work atleast.

**Comment by Narigo** [comment]
It's online over here: https://github.com/Narigo/scalajs-fun
Be aware that this is my current GitHub streak project, so you can see the progress and a lot of trying out there.

I didn't know about the Union type with `|`. This is great! :) PR follows - I didn't know how to test, though :/

**Comment by LukaJCB** [comment]
I'll go ahead and close this, if you don't have any objections :)

**Comment by Narigo** [comment]
If you would cut a release then, so no one else runs into this.... :)

Am 04.11.2016 00:55 schrieb "LukaJCB" notifications@github.com:
